### ISSUE TITLE
incompatible change in boards.txt which will break make flash

### ISSUE THREAD

**Issue by everslick** [plerup/makeEspArduino#102]
The next ESP32 Core release will break `make flash`. The reason is that the upload tool will change from esptool to esptool_py, thus the string `tools.esptool.upload.pattern` becomes `tools.esptool_py.upload.pattern`.

The Arduino Core maintainer @me-no-dev suggested to read the tool name also from boards.txt. It can be found in `${BOARD).upload.tool`.

I think it is only the perl code that is affected.

**Comment by me-no-dev** [comment]
This change was required because 8266 Arduino uses the same tool name (esptool) but the tool is in fact a different one, so in some installation cases, one of the cores was not able to flash because it was looking for the wrong esptool. Change was suggested by the Arduino IDE maintainers themselves.

**Comment by everslick** [comment]
This is the corresponding [commit](https://github.com/espressif/arduino-esp32/commit/2db811f7f3bb13a96a4459269e620cfcb3e18e54) for reference.

**Comment by plerup** [comment]
Ok, fix is coming

**Comment by everslick** [comment]
Works for me on ESP8266, ESP32 (pre 1.0.1-RC2) and ESP32 (HEAD).
